# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'clypr' do
  pod 'Stripe', '~> 11.2.0'

  # Required by RNFirebase
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Database'
  pod 'Firebase/Messaging'
  pod 'Firebase/Storage'

end
